### ISSUE TITLE
Permission denied during cleanup

### ISSUE THREAD

**Issue by ahmedbodi** [mdklatt/ansible-python3-role#11]
`RUNNING HANDLER [mdklatt.tmpdir : tmpdir remove] *******************************
fatal: [electrumx.multicoin.co]: FAILED! => {"changed": false, "msg": "rmtree failed: [Errno 13] Permission denied: '/tmp/ansible.nslmf_jp'"}`

**Comment by mdklatt** [comment]
@ahmedbodi 

It looks like you're doing a pyenv installation as a user other than `ansible_user_id`. You need to set `tmpdir_force` to `true`, which will remove the `python3_tmpdir` directory with privilege escalation.

``` yaml

roles:
  - name: python3
    python3_pyenv: "..."
    tmpdir_force: true
```
